[project]
name = "cosirl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blenderproc>=2.8.0",
    "gym>=0.26.2",
    "gymnasium>=1.1.1",
    "meshio>=5.3.5",
    "numpy>=2.2.4",
    "torch>=2.6.0",
]
